### ISSUE TITLE
Handle comment not found during `handle-pr-comment` processing

### ISSUE THREAD

**Issue by webstech** [gitgitgadget/gitgitgadget#1110]
If a comment was deleted before the job runs to handle it, gitgitgadget should fail more gracefully or not at all.  A message should be issued to indicate the comment was not found.

This appeared to happen for git/git pr# 1365 recently.

**Comment by derrickstolee** [comment]
Yes, this happened because I accidentally ran `/submit` on the wrong PR and deleted the `/submit` comment quickly. (It also happened to have not changed since the previous version, so maybe GGG wouldn't have submitted a new version, anyway.)

The current behavior of "don't submit" was a good end result. Maybe it shouldn't have an error, but it's a nice feature to "unsubmit" by a quick deletion of the command message.

**Comment by webstech** [comment]
> Yes, this happened because I accidentally ran `/submit` on the wrong PR and deleted the `/submit` comment quickly.

Thanks for confirming.  Someone appeared to be spam commenting on some PRs yesterday and I wondered if that was the case here but apparently not.

Another option is to update the comment to remove the /submit command.  That can be deleted later to avoid an error until this is updated.

It would be nice if this was not an error but ggg could still notify someone to verify there is not an issue.
