### ISSUE TITLE
Strip out template from cover letter and refuse to send an empty one

### ISSUE THREAD

**Issue by dscho** [gitgitgadget/gitgitgadget#136]
When opening a PR on GitGitGadget, the default PR description contains this text:

> Thanks for taking the time to contribute to Git! Please be advised that the Git community does not use github.com for their contributions. Instead, we use a mailing list (git@vger.kernel.org) for code submissions, code reviews, and bug reports. Nevertheless, you can use GitGitGadget (https://gitgitgadget.github.io/) to conveniently send your Pull Requests commits to our mailing list.

This text comes directly from the template in git.git's `master` (which we do _not_ want to modify in GitGitGadget, or at least we _cannot_ without adding commits that do not exist in git.git).

The idea is that the contributor reads it, and then deletes it, but that second step is easy to forget.

Let's teach GitGitGadget to detect e.g. the bread-crumb "Thanks for taking the time to contribute" in the PR description, and if found, gently refuse to send the patch series.

**Comment by sunshineco** [comment]
Refusing to send the patch series outright could be considered unnecessarily hostile if the user has otherwise composed appropriate cover-letter material and has simply forgotten to remove the blurb. An alternative would be to detect the _"Thanks for..."_ blurb, remove it automatically, and then send the patch series if the removal does not result in an empty message, or refuse to send the series if the result is empty.

**Comment by dscho** [comment]
> An alternative would be to detect the _"Thanks for..."_ blurb, remove it automatically, and then send the patch series if the removal does not result in an empty message, or refuse to send the series if the result is empty.

I like this idea a lot! Thank you!

**Comment by dscho** [comment]
Addressed via #144
