### ISSUE TITLE
Could merged PRs appear as "Merged" instead of "Closed" ?

### ISSUE THREAD

**Issue by phil-blain** [gitgitgadget/gitgitgadget#151]
I'm talking about the purple (merged) vs red (closed) distinction. 

I don't know if it would be possible to do that with the GitHub API, but it would add another visual hint as to which closed PRs were integrated upstream (in addition to the `master` label).

**Comment by dscho** [comment]
> I don't know if it would be possible to do that with the GitHub API, but it would add another visual hint as to which closed PRs were integrated upstream (in addition to the `master` label).

The only way I am aware of doing this is by force-pushing the merged version to the PR branch. While some contributors allow that (["Allow edits from maintainers"](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)), I feel that would be inappropriate, just to get that visual nicety.

**Comment by dscho** [comment]
> While some contributors allow that (["Allow edits from maintainers"](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)), I feel that would be inappropriate

Oh, and I do not even think that the GitGitGadget App would be allowed to do that, either.

**Comment by dscho** [comment]
FWIW here is the documentation of the GitHub API to merge a PR: https://developer.github.com/v3/pulls/#merge-a-pull-request-merge-button. And this is the API function we use to close the PR: https://developer.github.com/v3/issues/#edit-an-issue.

**Comment by dscho** [comment]
Actually, we use this API function to close the PR: https://developer.github.com/v3/pulls/#update-a-pull-request. But you will notice that this function, too, only allows "open" or "closed" as `state`.

**Comment by phil-blain** [comment]
To quote you, thanks for enlightening me! :)

**Comment by dscho** [comment]
So there is actually a super-dirty trick that we _might_ potentially use: force-push `master` (or whatever the target branch is at) to the contributor's branch. This requires the "Allow maintainers to make changed" checkbox to be checked, which it is by default, and most contributors seem to not even notice (let alone change) it when opening PRs.

However, this requires write permission, which we positively do _not_ want to have on git/git.

So I think that we simply cannot fulfill this wish, at least not without changes to the GitHub API. And probably not even then because it would still require some sort of write permission.

@phil-blain do you agree that we should close this ticket at this stage?

**Comment by phil-blain** [comment]
Yes, no problem with closing!
