### ISSUE TITLE
Disallow patches with bogus author emails

### ISSUE THREAD

**Issue by dscho** [gitgitgadget/gitgitgadget#182]
When anybody tries to respond to a mail sent by GitGitGadget, they will send the message to the recorded address. If that address is of the form `somebody@noreply.github.com`, we _know_ it is bogus. See e.g. [this mail](https://lore.kernel.org/git/b032358ca97df3bd5605ff356196f82a1f16a320.1578322213.git.gitgitgadget@gmail.com).

As part of the push validation (and before sending any mails), GitGitGadget should ensure that no such bogus email addresses are used.

**Comment by rosti-il** [comment]
@dscho The official main goal of the GitGitGadget project is "[to make contributions to the Git project (almost) as easy as opening a GitHub PR](https://github.com/gitgitgadget/gitgitgadget/blob/main/README.md)". GitHub allows to use a hidden email address of the `ID+username@users.noreply.github.com` format for protecting from spammers, scammers and other predators. Such emails are [officially supported](https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/managing-email-preferences/setting-your-commit-email-address) by GitHub and are widely used by many developers.

With the  https://github.com/gitgitgadget/gitgitgadget/commit/6af2a974e69d06f334a3409ac5f6cb390ef73d07 change all such GutHub users are unable to contribute into the Git project. For example [I can't](https://github.com/gitgitgadget/git/pull/979#issuecomment-860100622), although [you /allow -ed me](https://github.com/gitgitgadget/git/pull/979#issuecomment-860089633).

If understand this issue right it's all about replying to such addresses by the mailing list users. I agree that returning emails back with "_NXDOMAIN Domain name not found: users.noreply.github.com_" is annoying but I can't agree with the current solution. Why not just exclude the `@users.noreply.github.com` addresses from the emails (from the Cc, etc. fields) sent into the mailing list by GitGitGdget after `/submit`? I.e. why not just to hide such email addresses? Anyway all GitHub PRs are submitted into the mailing list with `gitgitgadget@gmail.com` in the "From" field.

Please remake the fix of this issue that way.

**Comment by tfidfwastaken** [comment]
@rosti-il I am not involved in the development of GitGitGadget, and not very sure about the complete reasoning behind this change.

My understanding is when you submit a patch to the Git project, reviews and discussion happen over email even if you submit it via GitGitGadget. Those emails are archived on a publicly viewable list. So I don't think there is any way where you can avoid using an anonymous email ID to contribute to Git at the moment anyway.

A possible workaround for this right now (since dscho is on vacation, so it may be a while before this is addressed) is to create a separate "burner" account and [connect it to GitHub](https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/managing-email-preferences/adding-an-email-address-to-your-github-account). Use that account as the primary account for the duration of your patch (and set it as public), and then change it back to a private address once it is done.

I understand this is not ideal for you right now, and I'm sorry about that.

**Comment by dscho** [comment]
The limitation does not actually come from GitGitGadget. It comes from the Git project itself. It is mentioned implicitly in https://git-scm.com/docs/SubmittingPatches#sign-off:

> Also notice that a real name is used in the `Signed-off-by` trailer. Please don’t hide your real name.

The rationale is that the Git project needs to be able to get ahold of patch contributors in case of follow-up questions/discussions.

That simply isn't possible with bogus email addresses and hidden identities.

So no, it would not help at all to revert GitGitGadget's behavior, all it would do is to annoy people all around and accomplish nothing.

**Comment by rosti-il** [comment]
> The limitation does not actually come from GitGitGadget. It comes from the Git project itself. It is mentioned implicitly in https://git-scm.com/docs/SubmittingPatches#sign-off:
> 
> > Also notice that a real name is used in the `Signed-off-by` trailer. Please don’t hide your real name.

I use my full real name. This issue is not about the name but about the email address.

> The rationale is that the Git project needs to be able to get ahold of patch contributors in case of follow-up questions/discussions.
> 
> That simply isn't possible with bogus email addresses and hidden identities.

Isn't it possible to get ahold of patch contributors by the [gitgitgadget](https://github.com/apps/gitgitgadget) bot through GitHub? The gitgitgadget bot already publish emails in appropriate PR comments at GitHub. Then GitHub sends email notification about every such comment to the PR author and to all other participants, without disclosing their private email addresses.

> So no, it would not help at all to revert GitGitGadget's behavior, all it would do is to annoy people all around and accomplish nothing.

Let's see how it works now with some other PR as an example.
This is one of the emails (in a raw format) that were sent by the gitgitgadget after `/submit`: https://lore.kernel.org/git/a91ac6c18938116c4a74e19466da456b67376fa5.1623316412.git.gitgitgadget@gmail.com/raw
This email has following fields with email addresses:
```
From:   "Johannes Schindelin via GitGitGadget" <gitgitgadget@gmail.com>
To:     git@vger.kernel.org
Cc:     Luke Shumaker <lukeshu@datawire.io>,
        Johannes Schindelin <johannes.schindelin@gmx.de>,
        Johannes Schindelin <johannes.schindelin@gmx.de>
```
And this is a reply to this email from Luke Shumaker in raw format:
https://lore.kernel.org/git/878s3h6wo8.wl-lukeshu@lukeshu.com/raw
```
From:   Luke Shumaker <lukeshu@lukeshu.com>
To:     "Johannes Schindelin via GitGitGadget" <gitgitgadget@gmail.com>
Cc:     git@vger.kernel.org, Luke Shumaker <lukeshu@datawire.io>,
        Johannes Schindelin <johannes.schindelin@gmx.de>
```
The `johannes.schindelin@gmx.de` email address is not bogus but just for this discussion let's assume it is bogus. What will happen if gitgitgadget just skip it during `/submit` processing? Then the above first email will be sent only to the following address fields:
```
From:   "Johannes Schindelin via GitGitGadget" <gitgitgadget@gmail.com>
To:     git@vger.kernel.org
Cc:     Luke Shumaker <lukeshu@datawire.io>
```
and Luke Shumaker would send his reply to the following addresses only:
```
From:   Luke Shumaker <lukeshu@lukeshu.com>
To:     "Johannes Schindelin via GitGitGadget" <gitgitgadget@gmail.com>
Cc:     git@vger.kernel.org, Luke Shumaker <lukeshu@datawire.io>
```
The gitgitgadget bot will receive this email from Luke and will publish it as a comment of the appropriate PR at GitHub. You, as the author of that PR, will get an email notification about this comment from GitHub. This comment will also contain a Message-ID of the Luke's email inside the `https://lore.kernel.org/git/xmqqim2l5ghj.fsf@gitster.g` URL used in that comment.
```
Message-ID: <xmqqim2l5ghj.fsf@gitster.g>
```
So if you reply to this comment on GitHub and keep that URL (or keep that Message-ID in any other predefined format) in the quotation then the gitgitgadget bot knows everything to make a valid reply from you and send it back to the mailing list and to all other addresses at From and Cc fields.

**Comment by dscho** [comment]
> The `johannes.schindelin@gmx.de` email address is not bogus but just for this discussion let's assume it is bogus. What will happen if gitgitgadget just skip it during `/submit` processing?

I tell you what _would_ happen. The people on the Git mailing list would get mad and would say that development does not happen on GitHub but on the mailing list and if I want to participate in the discussion about my patch I have to be able to receive emails.

If you're still disagreeing, by my guest and open a discussion. On the Git mailing list, of course: git@vger.kernel.org (you don't need to be subscribed, but you have to send plain text messages, not even alternative HTML allowed, and I hear that hotmail.com is blocked, too).

**Comment by rosti-il** [comment]
> A possible workaround for this right now (since dscho is on vacation, so it may be a while before this is addressed) is to create a separate "burner" account and [connect it to GitHub](https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/managing-email-preferences/adding-an-email-address-to-your-github-account). Use that account as the primary account for the duration of your patch (and set it as public), and then change it back to a private address once it is done.

This is how I had [contributed](https://docs.freebsd.org/en/articles/contributors/#contrib-additional) to the FreeBSD project through their mailing lists. Although I did it a long time ago I still receive many spam, scam and other garbage and in contrast to my private mailbox many of that garbage isn't detected by Gmail. So I don't check that mailbox very often. It could take months or even years between checks.

Technically I can amend my commit with that address and manually check mails in that spammed mailbox from my home computer. But this would be very annoying. I prefer a win-win solution.

**Comment by webstech** [comment]
> This is how I had [contributed](https://docs.freebsd.org/en/articles/contributors/#contrib-additional) to the FreeBSD project through their mailing lists.

Maybe being listed in a well known document is causing the spam.  I have not heard about commits being used to harvest email addresses.
