### ISSUE TITLE
Do not claim "was integrated into pu"

### ISSUE THREAD

**Issue by gitster** [gitgitgadget/gitgitgadget#230]
It is perfectly good to notify authors and stakeholders when a topic gets merged to 'next' and below, but 'pu' is merely "the maintainer happened to have looked at it and found it interesting enough", and not a useful gauge of topic's maturity or quality in any sense.

To help set the expectation level correctly, we may want to exclude 'pu' (and 'jch' if GGG keeps track of it) from such a notification.

**Comment by sunshineco** [comment]
On the other hand, there is some value in knowing that a submission has made it into `pu` since it means that the author doesn't need to worry about _pinging_ about a potentially overlooked topic. It's true that "_What's Cooking_" provides similar value, but there is a good chance that users of GitGitGadget do not follow the Git mailing list or check that particular source.

As an alternative to suppressing merge messages for `pu` altogether, perhaps the message can instead be annotated with a warning that presence in `pu` does not necessarily mean outright acceptance.

**Comment by gitster** [comment]
Presence in 'pu' does not even mean it will be kept there, so I am not sure if it is a good idea (unless there is a matching "the changes was ejected out of 'pu'" notice that the author can react on).

**Comment by dscho** [comment]
> Presence in 'pu' does not even mean it will be kept there

Right. But it is a significant step over "submitted". I use the absence `pu` label to determine whether I need to send a gentle ping, for example. And I use link in the message to quickly go to the merge commit, so if we were to skip "was integrated into pu", I would need some alternate means to get at that information quickly.

**Comment by dscho** [comment]
> unless there is a matching "the changes was ejected out of 'pu'" notice that the author can act on

I think we only have that in the console log for now, as it is not quite _that_ easy: the message says that the upstream commit previously associated with the tip commit of the PR is no longer in `pu`. It gets even messier when only a subset of the patches are accepted into `pu`, or when a subset of the patches gets accepted early (see e.g. `hn/reftable`).

**Comment by dscho** [comment]
I'll just close this for now.
