### ISSUE TITLE
Submitting patches that require conflict-resolution is broken

### ISSUE THREAD

**Issue by derrickstolee** [gitgitgadget/gitgitgadget#25]
When a PR needs to resolve conflicts, GitGitGadget does not submit the request (and does so silently). See this PR for an example:

https://github.com/gitgitgadget/git/pull/10/

Earlier in that PR, I tried to submit v2, but it complained about the merge-base relative to the topic. The merge-base was calculated based on the conflict-resolution commit.

Somehow, GitHub PRs likely have two possible "tips" for the pull request: the ref value and the PR merge commit. We will want to specifically pick the ref value to compute our merge-base.

**Comment by dscho** [comment]
I think the problem is the target branch... Previously, I only had the VSTS build mirror `maint`, `master`, `next` and `pu`. Now it mirrors all of the branches in https://github.com/gitster/git. That way, you can trivially pick the correct target branch, and the merge base will be trivially correct.
