### ISSUE TITLE
Great Project - Many Questions

### ISSUE THREAD

**Issue by softworkz** [gitgitgadget/gitgitgadget#805]
Hi,

my first computer didn't have graphics, and the only games were text adventures where you typed F L R B to move and you got some short text responses, telling what's happening or why you have died, Luckily, the world is evolving and new technologies and ideas are allowing us to work or play in increasingly better better and more efficient ways.
Retroactive behaviors have always existed in history - but seeing ~~many~~ a certain group of software developers being fixated on ancient and inefficient procedures to work an collaborate....I don't get this together.

Doing some ffmpeg development at times and a bit more recently, their e-mail based GIT workflow has always been an annoyance to me for a number of reasons. So it should be no surprise that I like this project. I had a similar idea a while ago, but found GitGitGadget just about this summer. From a quick look, I had seen that it would take more than a few hours to adopt this for ffmpeg, so I had put it aside but kept thinking about it.  What should I say - the level of annoyance had approached another high and so I decided to give it a go :-)

It wasn't too difficult from a large scale view. There are lots of good information on the [Wiki page](https://github.com/gitgitgadget/gitgitgadget/issues/690) and in the [recent conversation about adoption](https://github.com/gitgitgadget/gitgitgadget/issues/690), just that the it's all mixed up a bit and you need to read more than twice 
 to get all the important bits. 
Adapting the code was really easy and took the least time actually. Setting up the git e-mail server took a while, it's not really well documented and information about public-inbox is rare.
The really unfortunate part is that the Azure pipeline definitions cannot be viewed. Even though the bash scripts are posted and explained here, it wasn't easy to infer how all these pipelines are meant to work and need to be set up.
I was able to figure out how it's meant to work in most cases, but a number of things are still a but unclear.

tbc..

**Comment by softworkz** [comment]
Let's start with those thing that I already got completed:

- [x] Fresh new server with 
  - Debian 
  - Postfix
  - .com domain + dns setup
  - new mail account for receiving from the ML
- [x] Installed the latest version of public-inbox
  configured and working
- [x] Created a new GitHub organization
  allowing for flexibility in terms of ownership
- [x] Forked ffmpeg
- [x] Forked GitGitGadget
- [x] Created a new Azure DevOps organization
- [x] Registered a Gmail account
- [x] Created GitHub and Azure accounts, with access tokens
- [x] Registered a new GitHub App
      - created a public/private key pair
      - installed to the forked ffmpeg repo
- [x] Set up and installed a private Azure DevOps build agent

(the checkboxes are somewhat pointless now, but it's just a copy/paste)

tbc..

**Comment by softworkz** [comment]
The most important question I have at this point is about that "Azure Function".

There are so many different components involved already (and it's a whole different thing than DevOps piipelines).
We have the DevOps piipelines, we have GitHub and we have our own build agent.

Why did you choose once another service over the one's that are already part of  the setup?
Couldn't this be just run as an Azure pipeline like the others?

Thanks,
softworkz

**Comment by dscho** [comment]
> The really unfortunate part is that the Azure pipeline definitions cannot be viewed.

It is here: https://github.com/gitgitgadget/gitgitgadget/tree/HEAD/azure-function/. If you search for `process.env`, you see that it uses the environment variables [`GITHUB_WEBHOOK_SECRET`](https://github.com/gitgitgadget/gitgitgadget/blob/66d96868a28128230c74543a6fb011467cb72a96/azure-function/index.js#L16) and [`GITGITGADGET_TRIGGER_TOKEN`](https://github.com/gitgitgadget/gitgitgadget/blob/66d96868a28128230c74543a6fb011467cb72a96/azure-function/index.js#L124), they need to be configured in the "Configuration" blade of the Function App, in the "Application settings" tab. In the same blade, under "Function runtime settings", the "Runtime version" is set to `~2`. The Function App is registered as running on Windows, but I think it might not even matter.

> What I didn't understood initially was the part "GitHub App backed by an Azure Function".

What that means is that the URL specified when registering the GitHub App points to the Azure Function, and the Azure Function then does some rudimentary processing and validating, and if everything is okay, triggers the corresponding Azure Pipeline (which is a Pipeline that is set up to _also_ be triggered on `pull_request` events, so that it runs both "automatically" when someone opens a PR and "manually" when the Azure Function processes e.g. a `/preview`).

> A problem is, that there's no option for polling in case of GitHub repos.

In Azure Pipelines, you can specify "Other" and then use a GitHub URL, which polls. That's what I use.

> 2. Pipeline: Mirror Git Inbox to Azure Git Repo
>
> There is no code shown for this, but from the log output of the gitgitgadget Azure task, one could see that it does pull/push from the Git inbox to an Azure Git repo.

If you have a stable enough Git Inbox, you don't really need the mirror on Azure Repos. GitGitGadget started out using public-inbox.org, which runs on a relatively weak machine, and eventually switched to lore.kernel.org, which was not originally available and is a lot more stable.

> Later I found out that the data in the Azure repo is not used anywhere, so I assume this is just for backup?

I _think_ we still start out new agents by cloning from Azure Repos, and only update from lore.kernel.org/git, but I might misremember.

> 3 Mirror Mailing List to GitHub PRs

I don't remember whether I documented this anywhere yet (wiki, maybe? I could look, but then I would not have time to send this reply), so here is what the Pipeline looks like here:

![image](https://user-images.githubusercontent.com/127790/146389682-7e61e9a8-844e-4dfd-aeab-0f0674439d95.png)

The `Variables` tab defines `GIT_CONFIG_PARAMETERS='user.name=GitGitGadget' 'user.email=gitgitgadget@gmail.com' 'gitgitgadget.workDir=$(Agent.HomeDirectory)/../git-worktree' 'gitgitgadget.loregitdir=$(Agent.HomeDirectory)/../lore-git'` and the two secret variables `gitgitgadget-git.privateKey` and `gitgitgadget.privateKey` (since you will only have to deal with one repository, not two, like `git/git` _and_ `gitgitgadget/git`, you will only need the latter, I think). The individual steps:

## Pull GitGitGadget, npm install & build

```sh
test -d .git || git init || exit 1

git rev-parse HEAD >.git/PRE_FETCH_HEAD
git fetch https://github.com/gitgitgadget/gitgitgadget main

# If the lore-specific adjustments are not yet in master, use Dscho's branch
#git grep -e -U99999 FETCH_HEAD lib/mail-archive-helper.ts ||
#git fetch https://github.com/dscho/gitgitgadget fix-lore-parsing

git reset --hard FETCH_HEAD

# If nothing was pulled, and misc-helper.js is up to date, we already built it
test ! -f build/script/misc-helper.js ||
test script/misc-helper.ts -nt build/script/misc-helper.js ||
test "$(git rev-parse HEAD)" != "$(cat .git/PRE_FETCH_HEAD)" ||
exit 0

npm install &&
npm run build ||
exit 1
```

## Force-fetch refs/notes/gitgitgadget

```sh
test ! -d $HOME/git-worktree ||
git -C $HOME/git-worktree fetch $(git config gitgitgadget.publishremote) +refs/notes/gitgitgadget:refs/notes/gitgitgadget
```

## Fetch latest lore.kernel.org/git updates

```sh
die () {
    echo "$*" >&2
    exit 1
}

# (transition-only) make sure we have an up to date https://public-inbox/git mirror
#export PUBLIC_INBOX_DIR="$HOME/public-inbox-git"
#test -d "$PUBLIC_INBOX_DIR" ||
#git clone --bare https://git-for-windows.visualstudio.com/git.public-inbox/_git/git.public-inbox "$PUBLIC_INBOX_DIR" ||
#die "Could not clone public-inbox/git to $PUBLIC_INBOX_DIR"
#git -C "$PUBLIC_INBOX_DIR" fetch https://public-inbox.org/git master:master ||
#die "Could not update $PUBLIC_INBOX_DIR to remote's master"

# make sure we have an up to date lore.kernel.org/git mirror
export LORE_GIT_DIR="$HOME/lore-git"
test -d "$LORE_GIT_DIR" ||
git clone --bare https://gitgitgadget@dev.azure.com/gitgitgadget/git/_git/lore-git "$LORE_GIT_DIR" ||
die "Could not clone lore-git to $LORE_GIT_DIR"
git -C "$LORE_GIT_DIR" fetch https://lore.kernel.org/git/0 master:master ||
die "Could not update $LORE_GIT_DIR to remote's master"
```

## Obtain GitHub App token

```sh
GIT_CONFIG_PARAMETERS="$GIT_CONFIG_PARAMETERS $EXTRA_CONFIG"
node build/script/misc-helper.js set-app-token $(git grep -q "'dscho': 12"  azure-function/index.js && echo "git dscho") &&
git config gitgitgadget.publishRemote \
    https://x-access-token:$(git config gitgitgadget.githubToken)@github.com/gitgitgadget/git
git config gitgitgadget.loregitdir "$HOME/lore-git"
```

Here, the step-specific environment variable `EXTRA_CONFIG='gitgitgadget.privateKey=$(gitgitgadget.privateKey)' 'gitgitgadget-git.privateKey=$(gitgitgadget-git.privateKey)'` is defined, to get make the secrets available to the script

## Process new mails

```sh
node build/script/misc-helper.js handle-new-mails
```

## Push refs/notes/gitgitgadget

```sh
git -C $HOME/git-worktree push $(git config gitgitgadget.publishremote) refs/notes/gitgitgadget
```

Here, the step has the Control Option "Run this task" set to "Even if a previous task has failed, unless the build was canceled".

> The other problem (found after hours) was the second line in the scripts:
> 
> ```c
> EXTRA_CONFIG = 'section.variable=value'
> 
> GIT_CONFIG_PARAMETERS="$GIT_CONFIG_PARAMETERS $EXTRA_CONFIG"
> ```
> 
> When GIT_CONFIG_PARAMETERS is empty before the first assignment, we get this result:
> 
> ```c
> GIT_CONFIG_PARAMETERS =>" 'section.variable=value'"
> ```

Right, the assumption here is that the `GIT_CONFIG_PARAMETERS` variable configures `user.name` and `user.email` so that Git notes can be created with `git notes add`.

> Why did you choose once another service over the one's that are already part of the setup?

The problem is that the GitHub App needs a URL, and it sends signed webhook payloads to that URL. No Azure Pipeline can be triggered using that method. Hence the Azure Function that simply parses the payload and turns it into a ("manual") trigger via an Azure Pipeline PAT.

Thank you for writing up your journey. And sorry that there were so many obstacles.

If you have any ideas how this could be documented better/streamlined better (we could potentially turn at least _some_ Azure Pipelines into GitHub workflows using PATs as secret variables to access the repository, or even the GitHub App secrets), I would be delighted to see that contributed back to this here project.

**Comment by softworkz** [comment]
> If you have any ideas how this could be documented better/streamlined better (we could potentially turn at least _some_ Azure Pipelines into GitHub workflows using PATs as secret variables to access the repository, or even the GitHub App secrets), I would be delighted to see that contributed back to this here project.

Thanks a lot for replying.

I think that the pieces you have written are quite good. Problems:

- These are just spread over multiple places (Design.md, Wiki, Issues) and unordered
- They have a high density of information where you can easily overlook important bits
- A few gaps exist in some areas (I can fill some of those)

A lot of improvement could be achieved already without writing a single line, only by moving all to a single place, adding a few more headings, paragraph and line breaks around important information.
A step-by-step prerequisite list might be useful as well (similar to the checkbox-list above, it's not the exact order I did, but close.

**Comment by softworkz** [comment]
> > The really unfortunate part is that the Azure pipeline definitions cannot be viewed.
> 
> It is here: [`HEAD`/azure-function/](https://github.com/gitgitgadget/gitgitgadget/tree/HEAD/azure-function/?rgh-link-date=2021-12-16T14%3A46%3A56Z). If you search for `process.env`, you see that it uses the environment variables [`GITHUB_WEBHOOK_SECRET`]

No, I meant the job definitions on DevOps. I was often wondering where you might have which variables defined or whether you have working folders defined  for certain bash scripts.

Actually I'm still not clear about the folder structure you are using. (Too) late I've seen the workDir definition pointing to a sibling folder of the agent installation, but I wasn't sure whether that also the Git repo or whether the Git repo is located elsewhere and the work-tree is just a working tree outside the repo folder?
Also, I have no idea to which folder you are cloning gitigitgadget and the mailbox repo. 
I have something totally different right now. It works, but is probably sub-optimal. I haven't looked at the details you posted above, so maybe it's already explained, though.

So that's what I meant was the the biggest obstacle, not being able to see the jobs and tasks in all detail. 
Not out of laziness wishing for a copy/paste solution, but rather because many questions are left open without seeing it.
You are probably one of a few dozen people on earth who know about custom git notes storage :-) 
I could only find out because in a few cases the pipeline log files are showing some commands...

**Comment by softworkz** [comment]
PS: Right now I'm checking out whether the Azure functions could be eliminated in a way that a GitHub action triggers the Azure pipeline directly: https://github.com/Azure/pipelines (the V2 version supports a "variables" parameter, so hopefully the GitHub event payload can be submitted to the pipeline directly. The index.js code from the function can be called inside the pipeline and the frequency of event invocations could be reduced by conditions in the GitHub action yml.
I _think_ this could work... let me see..

**Comment by dscho** [comment]
> I think that the pieces you have written are quite good. Problems:
> 
>     * These are just spread over multiple places (Design.md, Wiki, Issues) and unordered
> 
>     * They have a high density of information where you can easily overlook important bits
> 
>     * A few gaps exist in some areas (I can fill some of those)
> 
> 
> A lot of improvement could be achieved already without writing a single line, only by moving all to a single place, adding a few more headings, paragraph and line breaks around important information. A step-by-step prerequisite list might be useful as well (similar to the checkbox-list above, it's not the exact order I did, but close.

Those are good points. TBH I never really thought that GitGitGadget would be used for anything else than `git.git` (hence the name: "`git.git` gadget").

I guess a good first step to remedy this would be to move the documentation from the wiki's "GitGitGadget's Azure Function and Azure Pipelines" page to a new `docs/` file?

> I meant the job definitions on DevOps. I was often wondering where you might have which variables defined or whether you have working folders defined for certain bash scripts.
> 
> Actually I'm still not clear about the folder structure you are using. (Too) late I've seen the workDir definition pointing to a sibling folder of the agent installation, but I wasn't sure whether that also the Git repo or whether the Git repo is located elsewhere and the work-tree is just a working tree outside the repo folder? Also, I have no idea to which folder you are cloning gitigitgadget and the mailbox repo. I have something totally different right now. It works, but is probably sub-optimal. I haven't looked at the details you posted above, so maybe it's already explained, though.

The idea is to share a persistent `~/lore-git` mirror, as well as a persistent `~/git-worktree` mirror (which is a misnomer because it is actually a bare clone), between the Azure Pipelines jobs. This requires a single agent to be in the `gitgitgadget` pool, of course, to serialize the work in order to prevent concurrent updates to said mirrors.

> So that's what I meant was the the biggest obstacle, not being able to see the jobs and tasks in all detail.

I can see that. The most obvious way forward would be to move to YAML-based definitions of the Azure Pipelines, or to move to GitHub workflows altogether.

The reason why I did not do that yet is simple: such a YAML-based definition would _have_ to live in `gitgitgadget/git`'s `main` branch, which would require the Git maintainer to change their ways (and from vast past experience I want to avoid that).

If we moved to, say, a GitHub workflow that lives in `gitgitgadget/gitgitgadget`'s `main` branch, it would no longer be present in the Checks tabs of the Pull Requests in `gitgitgadget/git`.

> Right now I'm checking out whether the Azure functions could be eliminated in a way that a GitHub action triggers the Azure pipeline directly: https://github.com/Azure/pipelines

I do not really like that direction much because Azure Pipelines runs come with a large overhead. _And_ you would have runs for _every single PR comment_, not only the pre-filtered ones that make it past the Azure Function. But maybe that's something you can live with? If so, I would like to learn from your experience, and we might then change `gitgitgadget/gitgitgadget` to do the same.

**Comment by softworkz** [comment]
I think we have gone past those initial questions, so I hope it's in your sense when I'm closing this.

And also: Thanks for welcoming me!
