### ISSUE TITLE
git-notes: error setting initial `git@vger.kernel.org <-> GitGitGadget` value in note

### ISSUE THREAD

**Issue by webstech** [gitgitgadget/gitgitgadget#888]
If the ggg options have been set, the initial attempt to set the processed mail tip fails due to the empty blob already being present.  If the ggg options have not been set, the note is created.

I do not understand the first add here so I can't offer a fix.  Should the second add be checking for the empty blob before setting it?
```
try {
    await this.notes("add", "-m", key, this.notesRef);
    await this.notes("remove", `${this.notesRef}^`);
} catch (reason) {
    await this.notes("add", "-m", key, emptyBlobName);
    await this.notes("remove", emptyBlobName);
}
```

Both `add`s fail with:
```
Error: git notes --ref=refs/notes/gitgitgadget add -m git@vger.kernel.org <-> GitGitGadget e69de29bb2d1d6434b8b29ae775ad8c2e48c5391 failed: 1,
error: Cannot add notes. Found existing notes for object e69de29bb2d1d6434b8b29ae775ad8c2e48c5391. Use '-f' to overwrite existing notes
```

**Comment by dscho** [comment]
> If the ggg options have been set, the initial attempt to set the processed mail tip fails due to the empty blob already being present.

Hmm. If the GitGitGadget options have been set, the notes ref should exist, and the `git --ref=refs/notes/gitgitgadget add -m <key> refs/notes/gitgitgadget` call should _not_ have failed. If it fails, then a _previous_ call that "annotated the notes ref" forgot to remove it.

The reason why we do that `add -m <key>`/ `remove` dance is that we need to have a blob with `<key>` as it contents, _and_ we need this blob to be reachable. If we annotate the tip commit of the notes ref itself, then we get exactly such a reachable blob.

This strategy fails if the notes ref does not yet exist, which is why we use the trick to annotate the empty blob, thereby _creating_ the notes ref.

So why bother removing the note at all? Just because it would unnecessarily clutter the tree associated with the notes ref.

My main question is: what does `reason` show if this code is called when the notes ref does _not yet_ exist?

**Comment by webstech** [comment]
I have to say I am not sure what caused the error situation.  After I deleted the original note with the empty blob, I could not recreate.  Regarding the `reason`, the git error messages were what I saw.

With PR #896 there are now tests for this.  They do not reproduce this problem as an ordering issue so I am closing this issue.
